# ----------------------------------------------------------------------
# Created Date: 18th April 2022
# Author: Dennis Cruceru
# License: Cisco Sample Code License, Version 1.1
# ----------------------------------------------------------------------
# 
# Copyright (c) 2022 Cisco and/or its affiliates.
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the 'License'). You may obtain a copy of the
# License at: 'https://developer.cisco.com/docs/licenses'
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an 'AS IS'
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
# ----------------------------------------------------------------------
#
- hosts: demo_dnac
  vars_files:
    - ../vars/credentials.yml
  gather_facts: false
  tasks:

  - name: Show all network_devices
    ansible.builtin.debug:
      msg: "{{ network_devices_result }}"

  - name: Get Network Device by id 1
    cisco.dnac.network_device_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      id: 0c4c83f7-1fce-46fe-a0a2-ac4b2e7dfbab
    register: network_device_result

  - name: Get Network Device by id 2
    cisco.dnac.network_device_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      id: 0c4c83f7-1fce-46fe-a0a2-e35jra224l12
    register: network_device_result2

  - name: Show network_device 1
    ansible.builtin.debug:
      msg: "{{ network_device_result }}"
  
  - name: Show network_device 2
    ansible.builtin.debug:
      msg: "{{ network_device_result }}"
      
